[package]
name = "passwordmanager-gui"
version = "1.0.0"

[dependencies]
common = { path = "../common" }
crypto = { path = "../crypto" }

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]
