[package]
name = "core"
version = "1.5.0"
edition = "2018"

[dependencies]
crypto = { path = "../crypto" }
event-sourcing = { path = "../event-sourcing" }
rand = "0.7.3"
clipboard = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
