[package]
name = "passwordmanager"
version = "1.1.0"
edition = "2018"

[dependencies]
crypto = { path = "../crypto" }
glob = { path = "../glob" }
event-sourcing = { path = "../event-sourcing" }
iced = "0.1"
dirs = "2.0"
clipboard = "0.5.0"
rand = "0.7.3"
serde_json = "1.0"