name: Continious integration

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: install gtk3 dev package
      run: sudo apt-get install libgtk-3-dev -y

    - name: run test
      run: cargo test --release
